spring:
  application:
    name: reuse-request
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./provision/db/h2
    username: sa
    password: